- hosts: default
  vars_files:
    - vars/main.yaml
  roles:
    - { role: geerlingguy.repo-epel}
    - { role: geerlingguy.repo-remi }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php }
    - { role: bennojoy.memcached }
    - { role: geerlingguy.redis }
    - { role: geerlingguy.ntp }
  tasks:
    - name: ensure additional php packages are installed
      yum: name={{ item }} state=installed enablerepo=remi
      with_items: additional_php_packages
